#cloud-config
bootcmd:
 - mkdir /dltest
 - echo "start------" >> /tmp/bootcmd.txt
 - mkdir /dltraining
 - id
 - [ sh, -c, "chown -R ubuntu: /dltraining/"]
 - [ sh, -c, "cd /home/ubuntu/ && git clone https://github.com/go4real/ec2-spot-labs.git"]
 - [ sh, -c, "chown -R ubuntu: /home/ubuntu/ec2-spot-labs"]
 - [ sh, -c, "chmod 777 /home/ubuntu/ec2-spot-labs/ec2-spot-deep-learning-training/run_training.sh"]
 - [ sh, -c, "/home/ubuntu/ec2-spot-labs/ec2-spot-deep-learning-training/run_training.sh"]
 - INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
 - INSTANCE_AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
 - AWS_REGION=ap-northeast-2
 - SPOT_FLEET_REQUEST_ID=$(aws ec2 describe-spot-instance-requests --region $AWS_REGION --filter "Name=instance-id,Values='$INSTANCE_ID'" --query "SpotInstanceRequests[].Tags[?Key=='aws:ec2spot:fleet-request-id'].Value[]" --output text)
 - aws ec2 cancel-spot-fleet-requests --region $AWS_REGION --spot-fleet-request-ids $SPOT_FLEET_REQUEST_ID --terminate-instances
 - echo "done------ $INSTANCE_ID $INSTANCE_AZ $AWS_REGION $SPOT_FLEET_REQUEST_ID" >> /tmp/bootcmd.txt

final_message: "The system is finally up, after $UPTIME seconds"